# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
# clone_folder: c:\projects\myproject

# environment variables
# environment:
  # my_var1: value1
  # my_var2: value2
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  # my_secure_var1:
  #   secure: FW3tJ3fMncxvs58/ifSP7w==

# scripts that run after cloning repository
# install:
  # by default, all script lines are interpreted as batch
  # - echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  # - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  # - cmd: echo This is batch again
  # - cmd: set MY_VAR=12345


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, AnyCPU. This setting is optional.
# platform: AnyCPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - AnyCPU

# build Configuration, i.e. Debug, Release, etc.
# configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: build.msbuild          # path to Visual Studio solution or project
  publish_wap: false              # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false        # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false            # package Azure Cloud Service projects and push to artifacts
  publish_nuget: false            # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed
  verbosity: normal

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests 
test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: build\deploy\*.zip

  # pushing all *.nupkg files in directory
  - path: build\deploy\*.nupkg


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider name are case-sensitive!
deploy: off
#   - provider: FTP
#     username: admin
#     password: psw
# 
#   - provider: WebDeploy
#     url: http://www.deploy.com/myendpoint
#     on:
#       branch: release
#       platform: x86
#       configuration: debug
# 
#   - provider: Environment
#     name: staging
#     on:
#       branch: staging
#       env_var1: value1
#       env_var2: value2

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script: